#define WIFI_SSID "Wokwi-GUEST"
#define WIFI_PASS ""

#define IO_USERNAME "YOUR_ADAFRUIT_USERNAME"
#define IO_KEY "YOUR_ADAFRUIT_ACTIVE_KEY"

#include "AdafruitIO_WiFi.h"
AdafruitIO_WiFi io(IO_USERNAME, IO_KEY, WIFI_SSID, WIFI_PASS);